### ISSUE TITLE
활동계획

### ISSUE THREAD

**Issue by jinwoo-chun** [20-1-SKKU-OSS/2020-1-OSS-6#11]
11주차 : 
선정 커뮤니티 / 프로젝트 활동 작성
선정 커뮤니티 소개 
선정 커뮤니티 활동 방법 정리
커뮤니티 활동 계획 정리
팀원 개인별 역할 및 활동 정하기
활동 시 이슈내용 및 고려사항 그리고 제안사항 작성

12주차 이후의 내용에 대한 의견 남겨주세요

**Comment by andy9705** [comment]
저희 프로젝트 두개 중 하나로 확정해서 진행해 나가야 하지 않을까요?

**Comment by jinwoo-chun** [comment]
프로젝트 알고리즘과 자료구조로 진행하기로 정해졌습니다.
