### ISSUE TITLE
홈페이지에 Issue활동 보고 post 작성 바랍니다.

### ISSUE THREAD

**Issue by Qayin-PJS** [20-1-SKKU-OSS/2020-1-OSS-6#42]
홈페이지에 Issue활동 보고 post 작성 바랍니다.

**Comment by lemonok** [comment]
해당 포스트를 생성했습니다.

**Comment by jinwoo-chun** [comment]
정적페이지 오류 issue , 문제/인풋/아웃풋 추가 issue, 정적페이지 테이블 디자인 issue에 대한 것들의 진행 상황 추가했습니다

**Comment by Qayin-PJS** [comment]
확인했습니다.
