### ISSUE TITLE
16288 BJ Problems

### ISSUE THREAD

**Issue by andy9705** [20-1-SKKU-OSS/2020-1-OSS-6#49]
visual studio로 돌려 본 결과 InputArr[N}, RollBackArr[K] 부분에서 N, K가 상수가 아니라 에러가 발생하였습니다. 이 부분을 고쳐야 할 거 같아요.        
int N, K;
cin >> N >> K;
int InputArr[N], RollBackArr[K];

**Comment by Qayin-PJS** [comment]
동적할당으로 수정하였습니다.
