### ISSUE TITLE
BJ problem 

### ISSUE THREAD

**Issue by andy9705** [20-1-SKKU-OSS/2020-1-OSS-6#50]
c++에 맞지 않은 함수들(scanf, printf)이 쓰여 있어서 한번 보시고 고쳐야 할 부분들은 고쳐야 할 거 같습니다.

**Comment by andy9705** [comment]
2011번은 .c로 하는게 좋을거 같아요

**Comment by andy9705** [comment]
제가 일단 수정할 부분은 했고 2011번만 수정하면 될 거 같아요

**Comment by Qayin-PJS** [comment]
2011번 수정했습니다. 
scanf와 printf는 cin과 cout에 비해 빠른 처리속도를 보여서 사용했습니다.
