### ISSUE TITLE
위키 페이지 추가

### ISSUE THREAD

**Issue by andy9705** [20-1-SKKU-OSS/2020-1-OSS-6#55]
위키 페이지 정적페이지에 올라온 알고리즘과 데이터구조 자료들을 바탕으로 업데이트 했습니다.

**Comment by ChungJuwon** [comment]
확인했습니다. 내용 추가후 wiki 마저 수정했습니다. 더 수정하시고 완료한후 comment나 close 해 주시면 감사하겠습니다.
